version: '3.8'
services:
  db-rest:
    container_name: db-ISMC
    image: postgres:latest
    restart: always
    ports:
      - "1502:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ISMC_database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - rest-data:/var/lib/postgresql/data

volumes:
  rest-data: